### ISSUE TITLE
Some questions about rumdetect2017

### ISSUE THREAD

**Issue by srtianxia** [dongkwan-kim/HBTP#21]
Hi, 
thank you for your amazing work! I would like to ask if your data is completely from rumdetect2017? 
But there are a couple of confusing things, like in the tree file, two nodes have the same tweet ID but different user ID.
(such as  ['16116288', '500378223977721856', '0.0']->['40957888', '500378223977721856', '0.77']), does that mean that the other user just retweets the source tweet? Another point is that some tweet ids in the tree file do not exist in source_tweets.txt, I guess these tweets are user comments on the source tweet or retweets when the comments, how should I get these tweets in source_tweets.txt does not exist, If possible, please provide me with a detailed description and data set containing all tweets content.
Thanks !

**Comment by dongkwan-kim** [comment]
Hi, srtianxia. Thank you for your interest.

Your questions are mainly about the rumdetect_acl_2017 dataset, and it might be more appropriate that you ask the original authors.

However, I will give you answers as far as I know.

> does that mean that the other user just retweets the source tweet?

Original paper says "a group of wide spread source tweets along with their propagation threads, i.e., replies and retweets"

> how should I get these tweets in source_tweets.txt does not exist

Sorry, I have no idea. When we were working on these datasets, there's no source_tweets.txt. I think the original authors added this file later.

Best, Dongkwan.

**Comment by srtianxia** [comment]
Thanks !
